if(${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	set(_SDL2_PREFIX "${CMAKE_CURRENT_LIST_DIR}/lib/x64")
else()
	set(_SDL2_PREFIX "${CMAKE_CURRENT_LIST_DIR}/lib/x86")
endif()
add_library(SDL2::SDL2 SHARED IMPORTED)
set_target_properties(SDL2::SDL2 PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include"
	IMPORTED_LOCATION "${_SDL2_PREFIX}/SDL2.dll"
	IMPORTED_IMPLIB "${_SDL2_PREFIX}/SDL2.lib"
)
add_library(SDL2::SDL2main STATIC IMPORTED)
set_target_properties(SDL2::SDL2main PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include"
	IMPORTED_LOCATION "${_SDL2_PREFIX}/SDL2main.lib"
)
set(_SDL2_PREFIX)
